name: Scrape Documentation
on: [push]

jobs:
  scrape-docs:
    runs-on: ubuntu-latest
    name: scrape and push content to Meilisearch instance
    steps:
      - uses: actions/checkout@v3
      - name: Run docs-scraper
        run: |
          docker run -t --rm \
          -e MEILISEARCH_HOST_URL=http://192.9.236.58 \
          -e MEILISEARCH_API_KEY=myMasterKey \
          -v $CONFIG_FILE_PATH:/docs-scraper/config.json \
          getmeili/docs-scraper:latest pipenv run ./docs_scraper config.json
          echo $HOST_URL
